package com.example.compose
import androidx.compose.ui.graphics.Color



val Yello100 = Color(0xFFFFEA8D)
val Purple500 = Color(0xFF6200EE)
val Purple700 = Color(0xFF3700B3)
val Teal200 = Color(0xFF03DAC5)
val Green300 = Color(0xFF81C784)
val Green800 = Color(0xFF2E7D32)
val Amber600 = Color(0xFFFFB300)




val md_theme_light_primary = Color(0xFF8D30B9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF7D8FF)
val md_theme_light_onPrimaryContainer = Color(0xFF310048)
val md_theme_light_secondary = Color(0xFF00687B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFAEECFF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F26)
val md_theme_light_tertiary = Color(0xFFB90065)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9E2)
val md_theme_light_onTertiaryContainer = Color(0xFF3E001E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF2D1600)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF2D1600)
val md_theme_light_surfaceVariant = Color(0xFFEBDFEA)
val md_theme_light_onSurfaceVariant = Color(0xFF4C444D)
val md_theme_light_outline = Color(0xFF7D747E)
val md_theme_light_inverseOnSurface = Color(0xFFFFEEE1)
val md_theme_light_inverseSurface = Color(0xFF4B2800)
val md_theme_light_inversePrimary = Color(0xFFE9B3FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF8D30B9)
val md_theme_light_outlineVariant = Color(0xFFCEC3CD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFE9B3FF)
val md_theme_dark_onPrimary = Color(0xFF510073)
val md_theme_dark_primaryContainer = Color(0xFF72089F)
val md_theme_dark_onPrimaryContainer = Color(0xFFF7D8FF)
val md_theme_dark_secondary = Color(0xFF48D7F8)
val md_theme_dark_onSecondary = Color(0xFF003641)
val md_theme_dark_secondaryContainer = Color(0xFF004E5D)
val md_theme_dark_onSecondaryContainer = Color(0xFFAEECFF)
val md_theme_dark_tertiary = Color(0xFFFFB0C9)
val md_theme_dark_onTertiary = Color(0xFF650034)
val md_theme_dark_tertiaryContainer = Color(0xFF8E004C)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF2D1600)
val md_theme_dark_onBackground = Color(0xFFFFDCC0)
val md_theme_dark_surface = Color(0xFF2D1600)
val md_theme_dark_onSurface = Color(0xFFFFDCC0)
val md_theme_dark_surfaceVariant = Color(0xFF4C444D)
val md_theme_dark_onSurfaceVariant = Color(0xFFCEC3CD)
val md_theme_dark_outline = Color(0xFF978E97)
val md_theme_dark_inverseOnSurface = Color(0xFF2D1600)
val md_theme_dark_inverseSurface = Color(0xFFFFDCC0)
val md_theme_dark_inversePrimary = Color(0xFF8D30B9)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFE9B3FF)
val md_theme_dark_outlineVariant = Color(0xFF4C444D)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFD376FF)
